FROM php:8.0.10-alpine

# Install PHP deps from psalm
RUN apk add php8-xml php8-dom

# Install Composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

WORKDIR /usr/src/app
